version: '3.1'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sykell
      MYSQL_USER: sykelluser
      MYSQL_PASSWORD: sykellpass
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
